# Generated by Django 4.0.2 on 2022-03-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='qte',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
