# Generated by Django 4.0.2 on 2022-03-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_alter_produit_qte'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='payer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
