# Generated by Django 4.0.2 on 2022-03-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_alter_commande_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='vendu_qte',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
