# Generated by Django 4.0.2 on 2022-03-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0006_produit_vendu_qte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='vendu_qte',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
