# Generated by Django 4.0.2 on 2022-03-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0008_boutique_avertissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
