# Generated by Django 4.0.2 on 2022-03-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_istechnique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='nature_notification',
            field=models.CharField(blank=True, choices=[('avertissement', 'avertissement'), ('etat commande', 'etat commande'), ('vente', 'vente'), ('annulation d achat', 'annulation d achat'), ('annulation de vente', 'annulation de vente'), ('desactivation boutique', 'desactivation boutique'), ('pour follower', 'pour follower'), ('note vendeur', 'note vendeur'), ('reactivation boutique', 'reactivation boutique'), ('probleme technique', 'probleme technique')], max_length=255),
        ),
    ]
